version: '3'
services:
    nodejs:
        image: node:alpine
        volumes:
        - .:/usr/app
        ports:
        - 3000:3000
        working_dir: /usr/app
        command: sh -c "yarn install"
        command: sh -c "yarn run dev"
